/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 6
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 3

enum ts_symbol_identifiers {
  sym_string = 1,
  anon_sym_LBRACK = 2,
  anon_sym_COMMA = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COLON = 7,
  sym__digit_sequence = 8,
  anon_sym_DOT = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  sym_user_defined_type = 14,
  anon_sym_Int = 15,
  anon_sym_Int32 = 16,
  anon_sym_Int64 = 17,
  anon_sym_Float = 18,
  anon_sym_Float32 = 19,
  anon_sym_Float64 = 20,
  sym_string_type = 21,
  sym_boolean_type = 22,
  anon_sym_LBRACK_RBRACK = 23,
  anon_sym_data = 24,
  anon_sym_EQ = 25,
  anon_sym_struct = 26,
  anon_sym_let = 27,
  sym_identifier = 28,
  anon_sym_return = 29,
  sym_source_file = 30,
  sym__literal = 31,
  sym_array_literal = 32,
  sym_struct_literal = 33,
  sym__struct_field = 34,
  sym__number = 35,
  sym_integer = 36,
  sym_float = 37,
  sym_expression = 38,
  sym__math_expression = 39,
  sym__arithmetic_operator = 40,
  sym_addition = 41,
  sym_subtraction = 42,
  sym_multiplication = 43,
  sym_division = 44,
  sym_negation = 45,
  sym_type_notation = 46,
  sym_type_declaration = 47,
  sym_type = 48,
  sym__primitive_type = 49,
  sym_integer_type = 50,
  sym_float_type = 51,
  sym_array_type = 52,
  sym_data_type = 53,
  sym_struct_type = 54,
  sym__struct_member = 55,
  sym__statement = 56,
  sym_let_assignment = 57,
  sym_return_statement = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_array_literal_repeat1 = 60,
  aux_sym_struct_literal_repeat1 = 61,
  aux_sym_struct_type_repeat1 = 62,
  alias_sym_data_type_name = 63,
  alias_sym_data_type_type = 64,
  alias_sym_field_name = 65,
  alias_sym_field_type = 66,
  alias_sym_field_value = 67,
  alias_sym_let_identifier = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_string] = "string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym__digit_sequence] = "_digit_sequence",
  [anon_sym_DOT] = ".",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_user_defined_type] = "user_defined_type",
  [anon_sym_Int] = "Int",
  [anon_sym_Int32] = "Int32",
  [anon_sym_Int64] = "Int64",
  [anon_sym_Float] = "Float",
  [anon_sym_Float32] = "Float32",
  [anon_sym_Float64] = "Float64",
  [sym_string_type] = "string_type",
  [sym_boolean_type] = "boolean_type",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_data] = "data",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_let] = "let",
  [sym_identifier] = "struct_name",
  [anon_sym_return] = "return",
  [sym_source_file] = "source_file",
  [sym__literal] = "_literal",
  [sym_array_literal] = "array_literal",
  [sym_struct_literal] = "struct_literal",
  [sym__struct_field] = "_struct_field",
  [sym__number] = "_number",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_expression] = "expression",
  [sym__math_expression] = "_math_expression",
  [sym__arithmetic_operator] = "_arithmetic_operator",
  [sym_addition] = "addition",
  [sym_subtraction] = "subtraction",
  [sym_multiplication] = "multiplication",
  [sym_division] = "division",
  [sym_negation] = "negation",
  [sym_type_notation] = "type_notation",
  [sym_type_declaration] = "type_declaration",
  [sym_type] = "type",
  [sym__primitive_type] = "_primitive_type",
  [sym_integer_type] = "integer_type",
  [sym_float_type] = "float_type",
  [sym_array_type] = "array_type",
  [sym_data_type] = "data_type",
  [sym_struct_type] = "struct_type",
  [sym__struct_member] = "_struct_member",
  [sym__statement] = "_statement",
  [sym_let_assignment] = "let_assignment",
  [sym_return_statement] = "return_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_struct_literal_repeat1] = "struct_literal_repeat1",
  [aux_sym_struct_type_repeat1] = "struct_type_repeat1",
  [alias_sym_data_type_name] = "data_type_name",
  [alias_sym_data_type_type] = "data_type_type",
  [alias_sym_field_name] = "field_name",
  [alias_sym_field_type] = "field_type",
  [alias_sym_field_value] = "field_value",
  [alias_sym_let_identifier] = "let_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_string] = sym_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__digit_sequence] = sym__digit_sequence,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_user_defined_type] = sym_user_defined_type,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Int32] = anon_sym_Int32,
  [anon_sym_Int64] = anon_sym_Int64,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_Float32] = anon_sym_Float32,
  [anon_sym_Float64] = anon_sym_Float64,
  [sym_string_type] = sym_string_type,
  [sym_boolean_type] = sym_boolean_type,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_let] = anon_sym_let,
  [sym_identifier] = sym_identifier,
  [anon_sym_return] = anon_sym_return,
  [sym_source_file] = sym_source_file,
  [sym__literal] = sym__literal,
  [sym_array_literal] = sym_array_literal,
  [sym_struct_literal] = sym_struct_literal,
  [sym__struct_field] = sym__struct_field,
  [sym__number] = sym__number,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_expression] = sym_expression,
  [sym__math_expression] = sym__math_expression,
  [sym__arithmetic_operator] = sym__arithmetic_operator,
  [sym_addition] = sym_addition,
  [sym_subtraction] = sym_subtraction,
  [sym_multiplication] = sym_multiplication,
  [sym_division] = sym_division,
  [sym_negation] = sym_negation,
  [sym_type_notation] = sym_type_notation,
  [sym_type_declaration] = sym_type_declaration,
  [sym_type] = sym_type,
  [sym__primitive_type] = sym__primitive_type,
  [sym_integer_type] = sym_integer_type,
  [sym_float_type] = sym_float_type,
  [sym_array_type] = sym_array_type,
  [sym_data_type] = sym_data_type,
  [sym_struct_type] = sym_struct_type,
  [sym__struct_member] = sym__struct_member,
  [sym__statement] = sym__statement,
  [sym_let_assignment] = sym_let_assignment,
  [sym_return_statement] = sym_return_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_struct_literal_repeat1] = aux_sym_struct_literal_repeat1,
  [aux_sym_struct_type_repeat1] = aux_sym_struct_type_repeat1,
  [alias_sym_data_type_name] = alias_sym_data_type_name,
  [alias_sym_data_type_type] = alias_sym_data_type_type,
  [alias_sym_field_name] = alias_sym_field_name,
  [alias_sym_field_type] = alias_sym_field_type,
  [alias_sym_field_value] = alias_sym_field_value,
  [alias_sym_let_identifier] = alias_sym_let_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__digit_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_user_defined_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float64] = {
    .visible = true,
    .named = false,
  },
  [sym_string_type] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__struct_field] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__math_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__arithmetic_operator] = {
    .visible = false,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_division] = {
    .visible = true,
    .named = true,
  },
  [sym_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_type_notation] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__primitive_type] = {
    .visible = false,
    .named = true,
  },
  [sym_integer_type] = {
    .visible = true,
    .named = true,
  },
  [sym_float_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_data_type] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_type] = {
    .visible = true,
    .named = true,
  },
  [sym__struct_member] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_data_type_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_data_type_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_let_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_field_name = 1,
  field_field_type = 2,
  field_field_value = 3,
  field_struct_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_field_name] = "field_name",
  [field_field_type] = "field_type",
  [field_field_value] = "field_value",
  [field_struct_name] = "struct_name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [3] = {.index = 0, .length = 3},
  [4] = {.index = 3, .length = 3},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 5},
  [8] = {.index = 15, .length = 4},
  [9] = {.index = 19, .length = 2},
  [10] = {.index = 21, .length = 2},
  [11] = {.index = 23, .length = 5},
  [12] = {.index = 28, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_field_name, 2, .inherited = true},
    {field_field_value, 2, .inherited = true},
    {field_struct_name, 0},
  [3] =
    {field_field_name, 3, .inherited = true},
    {field_field_type, 3, .inherited = true},
    {field_struct_name, 1},
  [6] =
    {field_field_name, 0},
    {field_field_value, 2},
  [8] =
    {field_field_name, 1, .inherited = true},
    {field_field_value, 1, .inherited = true},
  [10] =
    {field_field_name, 2, .inherited = true},
    {field_field_name, 3, .inherited = true},
    {field_field_value, 2, .inherited = true},
    {field_field_value, 3, .inherited = true},
    {field_struct_name, 0},
  [15] =
    {field_field_name, 0, .inherited = true},
    {field_field_name, 1, .inherited = true},
    {field_field_value, 0, .inherited = true},
    {field_field_value, 1, .inherited = true},
  [19] =
    {field_field_name, 0},
    {field_field_type, 2},
  [21] =
    {field_field_name, 1, .inherited = true},
    {field_field_type, 1, .inherited = true},
  [23] =
    {field_field_name, 3, .inherited = true},
    {field_field_name, 4, .inherited = true},
    {field_field_type, 3, .inherited = true},
    {field_field_type, 4, .inherited = true},
    {field_struct_name, 1},
  [28] =
    {field_field_name, 0, .inherited = true},
    {field_field_name, 1, .inherited = true},
    {field_field_type, 0, .inherited = true},
    {field_field_type, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_data_type_name,
    [3] = alias_sym_data_type_type,
  },
  [2] = {
    [1] = alias_sym_let_identifier,
  },
  [4] = {
    [1] = sym_identifier,
  },
  [5] = {
    [0] = alias_sym_field_name,
    [2] = alias_sym_field_value,
  },
  [9] = {
    [0] = alias_sym_field_name,
    [2] = alias_sym_field_type,
  },
  [11] = {
    [1] = sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_expression, 2,
    sym_expression,
    alias_sym_field_value,
  sym_type, 3,
    sym_type,
    alias_sym_data_type_type,
    alias_sym_field_type,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 27,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
  sym_type,
  sym_type_declaration,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 10},
  [sym_type] = {.index = 10, .length = 6},
  [sym_type_declaration] = {.index = 16, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_addition,
    sym_array_literal,
    sym_division,
    sym_float,
    sym_integer,
    sym_multiplication,
    sym_negation,
    sym_string,
    sym_struct_literal,
    sym_subtraction,
  [10] =
    sym_array_type,
    sym_boolean_type,
    sym_float_type,
    sym_integer_type,
    sym_string_type,
    sym_user_defined_type,
  [16] =
    sym_data_type,
    sym_struct_type,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 2,
        '*', 37,
        '+', 35,
        ',', 27,
        '-', 36,
        '.', 34,
        '/', 38,
        ':', 31,
        '=', 69,
        'B', 51,
        'F', 47,
        'I', 49,
        'S', 54,
        '[', 26,
        ']', 28,
        'd', 6,
        'l', 8,
        'r', 9,
        's', 13,
        '{', 29,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '_') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'B') ADVANCE(51);
      if (lookahead == 'F') ADVANCE(47);
      if (lookahead == 'I') ADVANCE(49);
      if (lookahead == 'S') ADVANCE(54);
      if (lookahead == '[') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(66);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 21:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 2,
        '*', 37,
        '+', 35,
        ',', 27,
        '-', 36,
        '.', 34,
        '/', 38,
        '=', 69,
        '[', 25,
        ']', 28,
        '_', 33,
        'd', 75,
        'l', 77,
        'r', 78,
        's', 82,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(66);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__digit_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__digit_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == '2') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == '2') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == '4') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == '4') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'a') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'g') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'i') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'l') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'l') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'n') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'n') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'o') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'o') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 'r') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 't') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 't') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_user_defined_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_Int);
      if (lookahead == '3') ADVANCE(39);
      if (lookahead == '6') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_Int32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_Int64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_Float);
      if (lookahead == '3') ADVANCE(40);
      if (lookahead == '6') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_Float32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Float64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_string_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_boolean_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_data);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 22},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 22},
  [32] = {.lex_state = 22},
  [33] = {.lex_state = 22},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 22},
  [36] = {.lex_state = 22},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 22},
  [43] = {.lex_state = 22},
  [44] = {.lex_state = 22},
  [45] = {.lex_state = 22},
  [46] = {.lex_state = 22},
  [47] = {.lex_state = 22},
  [48] = {.lex_state = 22},
  [49] = {.lex_state = 22},
  [50] = {.lex_state = 22},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 20},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 20},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 20},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 20},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 20},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 20},
  [73] = {.lex_state = 20},
  [74] = {.lex_state = 20},
  [75] = {.lex_state = 20},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 21},
  [85] = {.lex_state = 21},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__digit_sequence] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_user_defined_type] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Int32] = ACTIONS(1),
    [anon_sym_Int64] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_Float32] = ACTIONS(1),
    [anon_sym_Float64] = ACTIONS(1),
    [sym_string_type] = ACTIONS(1),
    [sym_boolean_type] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym__literal] = STATE(24),
    [sym_array_literal] = STATE(24),
    [sym_struct_literal] = STATE(24),
    [sym__number] = STATE(27),
    [sym_integer] = STATE(27),
    [sym_float] = STATE(27),
    [sym_expression] = STATE(2),
    [sym__math_expression] = STATE(19),
    [sym__arithmetic_operator] = STATE(19),
    [sym_addition] = STATE(19),
    [sym_subtraction] = STATE(19),
    [sym_multiplication] = STATE(19),
    [sym_division] = STATE(19),
    [sym_negation] = STATE(19),
    [sym_type_declaration] = STATE(2),
    [sym_data_type] = STATE(46),
    [sym_struct_type] = STATE(46),
    [sym__statement] = STATE(2),
    [sym_let_assignment] = STATE(2),
    [sym_return_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_string] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym__digit_sequence] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_data] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_return] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_data,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(46), 2,
      sym_data_type,
      sym_struct_type,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(27), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(3), 6,
      sym_expression,
      sym_type_declaration,
      sym__statement,
      sym_let_assignment,
      sym_return_statement,
      aux_sym_source_file_repeat1,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [62] = 15,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_string,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      sym__digit_sequence,
    ACTIONS(36), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      anon_sym_data,
    ACTIONS(42), 1,
      anon_sym_struct,
    ACTIONS(45), 1,
      anon_sym_let,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_return,
    STATE(46), 2,
      sym_data_type,
      sym_struct_type,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(27), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(3), 6,
      sym_expression,
      sym_type_declaration,
      sym__statement,
      sym_let_assignment,
      sym_return_statement,
      aux_sym_source_file_repeat1,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [124] = 10,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_RBRACK,
    STATE(71), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(51), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [165] = 10,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(56), 1,
      anon_sym_RBRACK,
    STATE(71), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(51), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [206] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(66), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(51), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [244] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(59), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(51), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [282] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(45), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(27), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [320] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(43), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(27), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [358] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(48), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(27), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [396] = 9,
    ACTIONS(5), 1,
      sym_string,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__digit_sequence,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(71), 1,
      sym_expression,
    STATE(24), 3,
      sym__literal,
      sym_array_literal,
      sym_struct_literal,
    STATE(51), 3,
      sym__number,
      sym_integer,
      sym_float,
    STATE(19), 7,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [434] = 3,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(60), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(58), 10,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [458] = 2,
    ACTIONS(66), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [479] = 4,
    ACTIONS(72), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(70), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
  [504] = 2,
    ACTIONS(78), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(76), 10,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [525] = 2,
    ACTIONS(82), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(80), 10,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [546] = 4,
    ACTIONS(72), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(86), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
  [571] = 2,
    ACTIONS(90), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(88), 10,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [592] = 6,
    ACTIONS(72), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(96), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_DASH,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(94), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [621] = 6,
    ACTIONS(106), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(44), 1,
      sym_type,
    ACTIONS(100), 3,
      sym_user_defined_type,
      sym_string_type,
      sym_boolean_type,
    ACTIONS(102), 3,
      anon_sym_Int,
      anon_sym_Int32,
      anon_sym_Int64,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_Float32,
      anon_sym_Float64,
    STATE(28), 4,
      sym__primitive_type,
      sym_integer_type,
      sym_float_type,
      sym_array_type,
  [649] = 6,
    ACTIONS(106), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(78), 1,
      sym_type,
    ACTIONS(100), 3,
      sym_user_defined_type,
      sym_string_type,
      sym_boolean_type,
    ACTIONS(102), 3,
      anon_sym_Int,
      anon_sym_Int32,
      anon_sym_Int64,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_Float32,
      anon_sym_Float64,
    STATE(28), 4,
      sym__primitive_type,
      sym_integer_type,
      sym_float_type,
      sym_array_type,
  [677] = 6,
    ACTIONS(106), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(68), 1,
      sym_type,
    ACTIONS(100), 3,
      sym_user_defined_type,
      sym_string_type,
      sym_boolean_type,
    ACTIONS(102), 3,
      anon_sym_Int,
      anon_sym_Int32,
      anon_sym_Int64,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_Float32,
      anon_sym_Float64,
    STATE(28), 4,
      sym__primitive_type,
      sym_integer_type,
      sym_float_type,
      sym_array_type,
  [705] = 6,
    ACTIONS(106), 1,
      anon_sym_LBRACK_RBRACK,
    STATE(32), 1,
      sym_type,
    ACTIONS(100), 3,
      sym_user_defined_type,
      sym_string_type,
      sym_boolean_type,
    ACTIONS(102), 3,
      anon_sym_Int,
      anon_sym_Int32,
      anon_sym_Int64,
    ACTIONS(104), 3,
      anon_sym_Float,
      anon_sym_Float32,
      anon_sym_Float64,
    STATE(28), 4,
      sym__primitive_type,
      sym_integer_type,
      sym_float_type,
      sym_array_type,
  [733] = 2,
    ACTIONS(94), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [751] = 2,
    ACTIONS(110), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [769] = 2,
    ACTIONS(114), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [787] = 3,
    ACTIONS(120), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(118), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [807] = 2,
    ACTIONS(124), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ,
  [825] = 2,
    ACTIONS(128), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [843] = 2,
    ACTIONS(132), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ,
  [861] = 2,
    ACTIONS(136), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(134), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ,
  [879] = 2,
    ACTIONS(140), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ,
  [897] = 2,
    ACTIONS(144), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(142), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [915] = 2,
    ACTIONS(148), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [933] = 2,
    ACTIONS(152), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [951] = 2,
    ACTIONS(156), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DASH,
  [969] = 3,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(158), 1,
      sym__digit_sequence,
    STATE(16), 10,
      sym__number,
      sym_integer,
      sym_float,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [988] = 3,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(158), 1,
      sym__digit_sequence,
    STATE(15), 10,
      sym__number,
      sym_integer,
      sym_float,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [1007] = 3,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(158), 1,
      sym__digit_sequence,
    STATE(17), 10,
      sym__number,
      sym_integer,
      sym_float,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [1026] = 3,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(158), 1,
      sym__digit_sequence,
    STATE(18), 10,
      sym__number,
      sym_integer,
      sym_float,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [1045] = 3,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(158), 1,
      sym__digit_sequence,
    STATE(14), 10,
      sym__number,
      sym_integer,
      sym_float,
      sym__math_expression,
      sym__arithmetic_operator,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_negation,
  [1064] = 2,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(162), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1079] = 2,
    ACTIONS(164), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(166), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1094] = 2,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(170), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1109] = 2,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(174), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1124] = 2,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(178), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1139] = 2,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(182), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1154] = 2,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(186), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1169] = 2,
    ACTIONS(188), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(190), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1184] = 2,
    ACTIONS(192), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_DASH,
    ACTIONS(194), 6,
      sym__digit_sequence,
      anon_sym_data,
      anon_sym_struct,
      anon_sym_let,
      sym_identifier,
      anon_sym_return,
  [1199] = 2,
    ACTIONS(116), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(120), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1211] = 3,
    ACTIONS(54), 1,
      anon_sym_RBRACK,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_array_literal_repeat1,
  [1221] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_struct_type_repeat1,
  [1231] = 3,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(67), 1,
      sym__struct_field,
  [1241] = 3,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_struct_literal_repeat1,
  [1251] = 3,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_array_literal_repeat1,
  [1261] = 3,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(70), 1,
      sym__struct_member,
  [1271] = 3,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_struct_type_repeat1,
  [1281] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_array_literal_repeat1,
  [1291] = 3,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym__struct_field,
  [1301] = 3,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_struct_literal_repeat1,
  [1311] = 3,
    ACTIONS(234), 1,
      anon_sym_COLON,
    ACTIONS(236), 1,
      anon_sym_EQ,
    STATE(83), 1,
      sym_type_notation,
  [1321] = 3,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__struct_member,
  [1331] = 3,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_struct_type_repeat1,
  [1341] = 3,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_struct_literal_repeat1,
  [1351] = 1,
    ACTIONS(249), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1356] = 1,
    ACTIONS(251), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1361] = 1,
    ACTIONS(253), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1366] = 2,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(67), 1,
      sym__struct_field,
  [1373] = 1,
    ACTIONS(255), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1378] = 1,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1383] = 2,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(65), 1,
      sym__struct_field,
  [1390] = 2,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(53), 1,
      sym__struct_member,
  [1397] = 2,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(70), 1,
      sym__struct_member,
  [1404] = 1,
    ACTIONS(257), 1,
      sym_identifier,
  [1408] = 1,
    ACTIONS(259), 1,
      anon_sym_LBRACE,
  [1412] = 1,
    ACTIONS(261), 1,
      anon_sym_EQ,
  [1416] = 1,
    ACTIONS(263), 1,
      anon_sym_EQ,
  [1420] = 1,
    ACTIONS(265), 1,
      anon_sym_LBRACE,
  [1424] = 1,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
  [1428] = 1,
    ACTIONS(269), 1,
      sym__digit_sequence,
  [1432] = 1,
    ACTIONS(271), 1,
      anon_sym_COLON,
  [1436] = 1,
    ACTIONS(273), 1,
      anon_sym_EQ,
  [1440] = 1,
    ACTIONS(275), 1,
      sym_user_defined_type,
  [1444] = 1,
    ACTIONS(277), 1,
      sym_user_defined_type,
  [1448] = 1,
    ACTIONS(279), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 165,
  [SMALL_STATE(6)] = 206,
  [SMALL_STATE(7)] = 244,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 358,
  [SMALL_STATE(11)] = 396,
  [SMALL_STATE(12)] = 434,
  [SMALL_STATE(13)] = 458,
  [SMALL_STATE(14)] = 479,
  [SMALL_STATE(15)] = 504,
  [SMALL_STATE(16)] = 525,
  [SMALL_STATE(17)] = 546,
  [SMALL_STATE(18)] = 571,
  [SMALL_STATE(19)] = 592,
  [SMALL_STATE(20)] = 621,
  [SMALL_STATE(21)] = 649,
  [SMALL_STATE(22)] = 677,
  [SMALL_STATE(23)] = 705,
  [SMALL_STATE(24)] = 733,
  [SMALL_STATE(25)] = 751,
  [SMALL_STATE(26)] = 769,
  [SMALL_STATE(27)] = 787,
  [SMALL_STATE(28)] = 807,
  [SMALL_STATE(29)] = 825,
  [SMALL_STATE(30)] = 843,
  [SMALL_STATE(31)] = 861,
  [SMALL_STATE(32)] = 879,
  [SMALL_STATE(33)] = 897,
  [SMALL_STATE(34)] = 915,
  [SMALL_STATE(35)] = 933,
  [SMALL_STATE(36)] = 951,
  [SMALL_STATE(37)] = 969,
  [SMALL_STATE(38)] = 988,
  [SMALL_STATE(39)] = 1007,
  [SMALL_STATE(40)] = 1026,
  [SMALL_STATE(41)] = 1045,
  [SMALL_STATE(42)] = 1064,
  [SMALL_STATE(43)] = 1079,
  [SMALL_STATE(44)] = 1094,
  [SMALL_STATE(45)] = 1109,
  [SMALL_STATE(46)] = 1124,
  [SMALL_STATE(47)] = 1139,
  [SMALL_STATE(48)] = 1154,
  [SMALL_STATE(49)] = 1169,
  [SMALL_STATE(50)] = 1184,
  [SMALL_STATE(51)] = 1199,
  [SMALL_STATE(52)] = 1211,
  [SMALL_STATE(53)] = 1221,
  [SMALL_STATE(54)] = 1231,
  [SMALL_STATE(55)] = 1241,
  [SMALL_STATE(56)] = 1251,
  [SMALL_STATE(57)] = 1261,
  [SMALL_STATE(58)] = 1271,
  [SMALL_STATE(59)] = 1281,
  [SMALL_STATE(60)] = 1291,
  [SMALL_STATE(61)] = 1301,
  [SMALL_STATE(62)] = 1311,
  [SMALL_STATE(63)] = 1321,
  [SMALL_STATE(64)] = 1331,
  [SMALL_STATE(65)] = 1341,
  [SMALL_STATE(66)] = 1351,
  [SMALL_STATE(67)] = 1356,
  [SMALL_STATE(68)] = 1361,
  [SMALL_STATE(69)] = 1366,
  [SMALL_STATE(70)] = 1373,
  [SMALL_STATE(71)] = 1378,
  [SMALL_STATE(72)] = 1383,
  [SMALL_STATE(73)] = 1390,
  [SMALL_STATE(74)] = 1397,
  [SMALL_STATE(75)] = 1404,
  [SMALL_STATE(76)] = 1408,
  [SMALL_STATE(77)] = 1412,
  [SMALL_STATE(78)] = 1416,
  [SMALL_STATE(79)] = 1420,
  [SMALL_STATE(80)] = 1424,
  [SMALL_STATE(81)] = 1428,
  [SMALL_STATE(82)] = 1432,
  [SMALL_STATE(83)] = 1436,
  [SMALL_STATE(84)] = 1440,
  [SMALL_STATE(85)] = 1444,
  [SMALL_STATE(86)] = 1448,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtraction, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtraction, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplication, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negation, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negation, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__math_expression, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 4, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_literal, 4, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_type, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_type, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_type, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_type, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 5, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 5, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_literal, 5, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 5, 0, 7),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_literal, 5, 0, 7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_literal, 6, 0, 7),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_literal, 6, 0, 7),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_type, 6, 0, 11),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_type, 6, 0, 11),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_type, 4, 0, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_type, 4, 0, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 4, 0, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_assignment, 4, 0, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_type, 5, 0, 4),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_type, 5, 0, 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 5, 0, 2),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_assignment, 5, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_type, 6, 0, 4),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_type, 6, 0, 4),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_type, 7, 0, 11),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_type, 7, 0, 11),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_literal_repeat1, 2, 0, 8), SHIFT_REPEAT(69),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_literal_repeat1, 2, 0, 8),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_type_repeat1, 2, 0, 12), SHIFT_REPEAT(74),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_type_repeat1, 2, 0, 12),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__struct_field, 3, 0, 5),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_literal_repeat1, 2, 0, 6),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__struct_member, 3, 0, 9),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_type_repeat1, 2, 0, 10),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_notation, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [267] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jewel_parser(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jewel_parser",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
